In [2]:
# Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
from google.colab import files
uploaded = files.upload()

Saving Dataset.csv to Dataset.csv


In [5]:
# Importing the dataset
dataset = pd.read_csv('Dataset.csv')

In [7]:
print(dataset)

     Gender  Glucose    BP  SkinThickness  ...   BMI  PedigreeFunction  Age  Outcome
0      Male      148  72.0           35.0  ...  33.6             0.627   50        1
1    Female       85  66.0           29.0  ...  26.6             0.351   31        0
2    Female      183  64.0            0.0  ...  23.3             0.672   32        1
3    Female       89  66.0           23.0  ...  28.1             0.167   21        0
4      Male      137   NaN           35.0  ...  43.1             2.288   33        1
..      ...      ...   ...            ...  ...   ...               ...  ...      ...
559    Male       85  74.0            0.0  ...  30.1             0.300   35        0
560    Male      125  76.0            0.0  ...  33.8             0.121   54        1
561    Male      198  66.0           32.0  ...  41.3             0.502   28        1
562    Male       87  68.0           34.0  ...  37.6             0.401   24        0
563    Male       99  60.0           19.0  ...  26.9             

In [8]:
#Print Total number of Rows & columns in dataset
print(dataset.shape)

(564, 9)


In [9]:
dataset.isnull().sum()

Gender               0
Glucose              0
BP                  16
SkinThickness       11
Insulin             12
BMI                 17
PedigreeFunction    18
Age                  0
Outcome              0
dtype: int64

In [10]:
# Extracting dependent and independent variables:
# Extracting independent variable:
X = dataset.iloc[:, :-1].values
# Extracting dependent variable:
y = dataset.iloc[:, -1].values

In [11]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

In [12]:
# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NAN, strategy= 'mean', fill_value=None, verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:, :]) 
#Replacing missing data with the calculated mean value  
X[:, :]= imputer.transform(X[:,:])

In [13]:
pd.DataFrame(X).isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64

In [14]:
pd.DataFrame(y).isnull().sum()

0    0
dtype: int64

In [15]:
print(X.shape)
print(X)

(564, 8)
[[1.0 148.0 72.0 ... 33.6 0.627 50.0]
 [0.0 85.0 66.0 ... 26.6 0.35100000000000003 31.0]
 [0.0 183.0 64.0 ... 23.3 0.672 32.0]
 ...
 [1.0 198.0 66.0 ... 41.3 0.502 28.0]
 [1.0 87.0 68.0 ... 37.6 0.401 24.0]
 [1.0 99.0 60.0 ... 26.9 0.49700000000000005 32.0]]


In [16]:
print(y.shape)
print(y)

(564,)
[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1
 1 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1
 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0
 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0 1 0 0 0 1
 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 0 1
 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 1 0 1
 0 1 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1
 1 1 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 1 1 0 0 0 0

In [17]:
# Splitting the Dataset into the Training set and Test set

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [18]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
print(X_train)

[[-1.09036182 -1.08588698 -3.64840873 ... -3.92391628 -0.52601928
  -1.01622781]
 [-1.09036182 -1.26828266 -1.00942745 ... -0.12894382 -0.6894698
  -0.59145192]
 [-1.09036182  2.34923169  0.04616506 ... -0.19015305 -0.95215814
   1.70233791]
 ...
 [-1.09036182  2.31883241  0.36284281 ... -0.02722683  1.1405923
  -0.33658638]
 [ 0.91712676  1.19405904 -0.16495344 ... -0.2023949  -0.29543729
   0.25809987]
 [ 0.91712676 -1.0554877   0.25728356 ... -0.23912044 -0.53769432
   0.17314469]]


In [20]:
print(X_test)

[[ 0.91712676 -0.47790138  0.36284281 ... -1.6714165   0.28539582
  -0.50649674]
 [-1.09036182 -0.62989778  0.57396132 ... -1.56123988 -0.58439447
  -0.2516312 ]
 [ 0.91712676 -0.32590497  0.36284281 ... -0.50844107  0.45468386
  -0.16667602]
 ...
 [ 0.91712676 -0.4475021  -0.01884634 ... -0.15342751 -1.05723348
   0.34305505]
 [-1.09036182  2.04523889 -0.05939419 ...  0.69125991 -0.67195725
   0.68287576]
 [-1.09036182  1.04206264 -0.37607194 ...  0.09140942 -0.72157616
  -0.84631745]]


In [21]:
# Fitting SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [22]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [23]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[102  14]
 [ 19  35]]


In [24]:
# calculate Accuracy
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Accuracy: 80.59


In [25]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
# calculate precision
# Precision = TruePositives / (TruePositives + FalsePositives)
precision = precision_score(y_test, y_pred, average='micro')
print('Precision: %.3f' % (precision*100))

Precision: 80.588


In [26]:
# calculate recall
# Recall = TruePositives / (TruePositives + FalseNegatives)
recall = recall_score(y_test, y_pred, average='micro')
print('Recall: %.3f' % (recall*100))

Recall: 80.588


In [27]:
# F-Measure = (2 * Precision * Recall) / (Precision + Recall)
# calculate score
score = f1_score(y_test, y_pred, average='micro')
print('F-Measure: %.3f' % (score*100))

F-Measure: 80.588


In [ ]:
import pickle 
  
saved_model=pickle.dump(classifier,open('/content/drive/My Drive/mid_term_1.pkl', 'wb')) 